### ISSUE TITLE
Flip cards for quizzes

### ISSUE THREAD

**Issue by ElBatanony** [TE-Flutter/assisteva#3]
https://pub.dev/packages/flip_card

Suggestion:

1. Create a quiz collection.
2. Create a questions collection.
3. Point to a quiz from the question. i.e., every question has a quiz.
4. Customize the question DocScreen, by using the flip card package

**Comment by khlebobul** [comment]
Hi, I made an app that solves this issue. I created a separate repository for this project

[GitHub](https://github.com/TE-Flutter/Flip-cards-App)

If you have any questions, I'm ready to help.

[flip_card: ^0.6.0](https://pub.dev/packages/flip_card)

**Comment by khlebobul** [comment]
https://user-images.githubusercontent.com/77191581/200382889-da779230-4a46-4606-8795-808b55363626.mov
